### ISSUE TITLE
Nan crash

### ISSUE THREAD

**Issue by comedinha** [Kefta/Entity-Crash-Catcher#17]
```
L 01/26/2016 - 02:01:05: Result: traitors win.
Crazy physics on [260][prop_physics] [Ang:-nan,nan,180.000000] [Pos:-nan,-nan,nan] - removing
prop_ragdoll[256]:SetAbsOrigin( -nan -nan nan ): Ignoring unreasonable position.
Segmentation fault (core dumped)
BFD: Warning: /root/steamcmd/gmod2/core is truncated: expected core file size >= 544530432, found: 1024000.
Cannot access memory at address 0xf77b5928
Cannot access memory at address 0xf77b5924
Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0xffcd50e0: 
debug.cmds:1: Error in sourced command file:
Cannot access memory at address 0xffcd50e0
email debug.log to linux@valvesoftware.com
Tue Jan 26 02:01:08 GMT 2016: Server restart in 10 seconds
```
Please back with Nan check

**Comment by Kefta** [comment]
I don't think it works, but I guess I'll try. ALSO, in the mean time, can you try removing some addons until you pinpoint which is causing the crashes? I need to find out what causes this issue

**Comment by comedinha** [comment]
It occurred to me one time, if I remove the addons do not know whether it will happen again... it's pretty rare

**Comment by Kefta** [comment]
I really need to find out how it happens

**Comment by DH1806** [comment]
---------------------------
ServerLog: 01:11.55 - KILL:	<something/world> killed PsychoGamer [innocent]
L 01/26/2016 - 19:25:46: 01:11.55 - KILL:	<something/world> killed PsychoGamer [innocent]
prop_ragdoll[231]:SetAbsOrigin( -nan -nan nan ): Ignoring unreasonable position.
Crazy physics on [243][prop_physics] [Ang:-nan,nan,180.000000] [Pos:-nan,-nan,nan] - removing
----------------------------

I installed the new version, but the Server still keeps crashing due these issues. :/

**Comment by comedinha** [comment]
Yes, after remove the nan check the crashes by nan are more frequent

**Comment by DH1806** [comment]
Is there any way to get the nan check back?

**Comment by Kefta** [comment]
Yes, I will reimplement it tonight, but it would be great if y'all could try and track down what could be causing these!

**Comment by DH1806** [comment]
I would really like to help you out there, but my lua knowledge goes not beyong general knowledge. :/

**Comment by Kefta** [comment]
I just need you to single it down to a specific addon -- do some removal and see what induces the crashes

**Comment by DH1806** [comment]
Thats what I got with your older version....
ServerLog: [GS] Froze prop_physics for moving too fast (3960.0002441406) 
L 01/28/2016 - 17:10:06: [GS] Froze prop_physics for moving too fast (3960.0002441406) 
ServerLog: [GS] Froze DH1806 for moving too fast (3559.4323730469) 
L 01/28/2016 - 17:10:06: [GS] Froze DH1806 for moving too fast (3559.4323730469) 
ServerLog: [GS] Froze prop_physics for moving too fast (3960) 
L 01/28/2016 - 17:10:07: [GS] Froze prop_physics for moving too fast (3960) 
ServerLog: [GS] Froze DH1806 for moving too fast (3960.0002441406) 
L 01/28/2016 - 17:10:08: [GS] Froze DH1806 for moving too fast (3960.0002441406) 
ServerLog: [GS] Froze prop_physics for moving too fast (3960) 
L 01/28/2016 - 17:10:08: [GS] Froze prop_physics for moving too fast (3960) 
ServerLog: [GS] Froze prop_physics for moving too fast (3959.9997558594) 
L 01/28/2016 - 17:10:09: [GS] Froze prop_physics for moving too fast (3959.9997558594) 
ServerLog: [GS] Froze DH1806 for moving too fast (2565.4406738281) 
L 01/28/2016 - 17:10:11: [GS] Froze DH1806 for moving too fast (2565.4406738281) 
ServerLog: [GS] Froze prop_physics for moving too fast (2335.7712402344) 
L 01/28/2016 - 17:10:11: [GS] Froze prop_physics for moving too fast (2335.7712402344) 
ServerLog: [GS] Froze DH1806 for moving too fast (2059.2292480469) 
L 01/28/2016 - 17:10:13: [GS] Froze DH1806 for moving too fast (2059.2292480469) 
ServerLog: [GS] Froze prop_physics for moving too fast (3960.0002441406) 
L 01/28/2016 - 17:10:13: [GS] Froze prop_physics for moving too fast (3960.0002441406) 
ServerLog: [GS] Froze prop_physics for moving too fast (3959.9997558594) 
L 01/28/2016 - 17:10:14: [GS] Froze prop_physics for moving too fast (3959.9997558594) 
prop_ragdoll[276]:SetAbsOrigin( -nan -nan nan ): Ignoring unreasonable position.
Crazy physics on [277][prop_physics] [Ang:-nan,nan,180.000000] [Pos:-nan,-nan,nan] - removing


Well, do you think it's because of an specific addon? Why so many people are having it then?

**Comment by comedinha** [comment]
Yeah, you old nan crash work...

**Comment by Kefta** [comment]
This has been fixed in the newest version. Please test!

**Comment by Kefta** [comment]
@comedinha @DH1806

**Comment by comedinha** [comment]
Added to server, in a few days I will have better news

**Comment by comedinha** [comment]
``L 01/31/2016 - 09:05:55: Lua Error: 
[ERROR] addons/helpers/lua/autorun/server/gs_crashcatcher.lua:229: table index is nil
  1. fn - addons/helpers/lua/autorun/server/gs_crashcatcher.lua:229
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110
